### ISSUE TITLE
AttributeError: 'list' object has no attribute 'merge'

### ISSUE THREAD

**Issue by t-moe** [Enteee/pdml2flow#7]
```
 cat in.txt | pdml2json > /dev/null                     
Traceback (most recent call last):
  File "/usr/bin/pdml2json", line 9, in <module>
    load_entry_point('pdml2flow==1.0', 'console_scripts', 'pdml2json')()
  File "/usr/lib/python3.5/site-packages/pdml2flow-1.0-py3.5.egg/pdml2flow/__init__.py", line 81, in pdml2json
  File "/usr/lib/python3.5/site-packages/pdml2flow-1.0-py3.5.egg/pdml2flow/__init__.py", line 102, in pdml2frame
  File "/usr/lib/python3.5/site-packages/pdml2flow-1.0-py3.5.egg/pdml2flow/__init__.py", line 115, in start_parser
  File "/usr/lib/python3.5/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.5/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.5/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/build/python/src/Python-3.5.1/Modules/pyexpat.c", line 414, in StartElement
  File "/usr/lib/python3.5/xml/sax/expatreader.py", line 322, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/usr/lib/python3.5/site-packages/pdml2flow-1.0-py3.5.egg/pdml2flow/pdmlhandler.py", line 47, in startElement
AttributeError: 'list' object has no attribute 'merge'
```

Input is a normal pdml file (2GB).

Any Idea what that could be?
I can send you the pcap file (100mb) via email/och, if you need it.

**Comment by Enteee** [comment]
This could happen if a frame contains a field ending in .raw or . show preceeded by a similar field not ending in .raw or .show. But this should not happen.. Added debug messages in commit a4142a8100d2d68d8a748a8b4e14958582e62df5 which might help solving this issue. Can you please re-run the test in debug and send me the last couple of debug messages before the program crashes.

**Comment by Enteee** [comment]
also this is a frame-local problem. Thus attaching the last frame beeing processed before the script crashes could help a lot.

**Comment by t-moe** [comment]
Sure I can try to fetch those debug messages for you. Or if you don't want to wait, you just run the dump I sent you (29.4 via email) yourself....

**Comment by t-moe** [comment]
```
[Debug: 1456145969.162531]  field: smb.offset
[Debug: 1456145969.162531]  field: smb.reserved
[Debug: 1456145969.162531]  field: smb.write.mode
[Debug: 1456145969.162531]  field: smb.write.mode.message_start
[Debug: 1456145969.162531]  field: smb.write.mode.raw
Traceback (most recent call last):
  File "/usr/bin/pdml2json", line 9, in <module>
    load_entry_point('pdml2flow==1.0', 'console_scripts', 'pdml2json')()
  File "/usr/lib/python3.5/site-packages/pdml2flow-1.0-py3.5.egg/pdml2flow/__init__.py", line 81, in pdml2json
  File "/usr/lib/python3.5/site-packages/pdml2flow-1.0-py3.5.egg/pdml2flow/__init__.py", line 102, in pdml2frame
  File "/usr/lib/python3.5/site-packages/pdml2flow-1.0-py3.5.egg/pdml2flow/__init__.py", line 115, in start_parser
  File "/usr/lib/python3.5/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.5/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.5/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/build/python/src/Python-3.5.1/Modules/pyexpat.c", line 414, in StartElement
  File "/usr/lib/python3.5/xml/sax/expatreader.py", line 322, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/usr/lib/python3.5/site-packages/pdml2flow-1.0-py3.5.egg/pdml2flow/pdmlhandler.py", line 48, in startElement
AttributeError: 'list' object has no attribute 'merge'
```

**Comment by Enteee** [comment]
exactly what I expected:

```
[Debug: 1456145969.162531]  field: smb.write.mode
[...]
[Debug: 1456145969.162531]  field: smb.write.mode.raw
```

Don't know how to fix this properly atm. I've to name the fields somehow If these names are beeing used by tshark later on I will run into a conflict. So I could:
- don't appen the value when the exception is raised
- rename raw to something extremly complex which is never used as fieldname
- do something else..

**Comment by Enteee** [comment]
added [a test](https://github.com/Enteee/pdml2flow/tree/master/test/pdml2flow_tests/issue-7) (currently skipped) which replicates the issue we're facing here. Note that pdml2flow does not raise this exception if this behaviour is split into two frames, as shown [here](https://github.com/Enteee/pdml2flow/tree/master/test/pdml2flow_tests/issue-7.1). So is this (same as in test_issue-7.1):

``` json

    "information": {
      "raw": [
        123,
        {
          "raw": [
            321
          ]
        }
      ]
    }
```

how you'd like to have to output formatted? Please tell me and I'll try to implement it.

**Comment by t-moe** [comment]
The proposed output is fine for me. I don't really care about the output format, as long as no exception is raised.
